//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Schedule.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public long id { get; set; }
        public string name { get; set; }
        public string stud_section { get; set; }
        public string stud_id { get; set; }
        public string stud_bday { get; set; }
    }
}
